### PR TITLE
Add telemetry support

### PR DESCRIPTION
**Pull request by garthk**
~~Builds on #31; see 1599662 for a smaller set of changes.~~ rebased!

We need something like this to let our error capture machinery know about problems encoding or sending events. If it doesn't suit the project, please let us know what alternative approach might?

### CODE REVIEW

**Comment by garthk** [comment]
@stueccles, any chance of a yes or no on this?

**Review by zachdaniel — APPROVED** [review]

**Comment by zachdaniel** [comment]
@garthk we'll put this branch on staging and confirm its behavior and if everything looks good we'll merge

**Comment by zachdaniel** [comment]
Things look good on our end :)

**Comment by stueccles** [comment]
CleanShot 2020-12-04 at 14 24 51@2x

Here are the metrics in Datadog

**Pull request merged**
